name = "kmmiio99o"
compatibility_date = "2024-01-15"

# Pages configuration
[pages]
# Build configuration
build.command = "cd nextjs-site && npm ci && npm run build"
build.destination_dir = "nextjs-site/out"

# Environment variables
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "production"

# Custom domains (configure these in Cloudflare Dashboard)
# This is just for reference - actual domain setup is done in the dashboard
