name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "nextjs-site/package-lock.json"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: nextjs-site/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('nextjs-site/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        working-directory: nextjs-site
        run: npm ci

      - name: Build with Next.js
        working-directory: nextjs-site
        run: npm run build

      - name: Copy build to root
        run: |
          # Remove old files but keep important ones
          find . -maxdepth 1 -type f -name "*.html" -delete || true
          find . -maxdepth 1 -type f -name "*.js" -delete || true
          find . -maxdepth 1 -type f -name "*.css" -delete || true
          find . -maxdepth 1 -type d -name "_next" -exec rm -rf {} + 2>/dev/null || true

          # Copy new files from Next.js build
          cp -r nextjs-site/out/* .

          # Create CNAME file for custom domain
          echo "kmmiio99o.workers.dev" > CNAME

          # Create .nojekyll file to prevent Jekyll processing
          touch .nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
